"""Static checks learned after transfer set 30's blind 0/3 artifact was frozen."""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any, Iterable

_SOURCE_SUFFIXES = {".pl", ".pm", ".fs", ".fsi", ".fsx", ".nim"}


def _safe_text(root: Path, relative: str) -> str:
    try:
        resolved_root = root.resolve()
        path = (resolved_root / relative).resolve()
        if not path.is_relative_to(resolved_root) or not path.is_file():
            return ""
        return path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return ""


def _line(text: str, offset: int) -> int:
    return text[: max(0, offset)].count("\n") + 1


def _finding(
    *,
    officer: str,
    capability: str,
    category: str,
    severity: str,
    root_cause: str,
    path: str,
    line_start: int,
    message: str,
    evidence: str,
    falsifiers: list[str],
    verification: str,
    confidence: float,
    supporting: Iterable[str] = (),
) -> dict[str, Any]:
    primary = f"{path}:{line_start}"
    return {
        "source": "static-transfer-30-officer",
        "officer": officer,
        "capability": capability,
        "category": category,
        "severity": severity,
        "root_cause": root_cause,
        "path": path,
        "line_start": line_start,
        "line_end": line_start,
        "evidence_ref": primary,
        "supporting_evidence_refs": list(dict.fromkeys([primary, *supporting])),
        "message": message,
        "evidence": evidence,
        "falsifiers_checked": falsifiers,
        "verification_test": verification,
        "confidence": confidence,
        "direct_evidence": True,
        "admission_hint": "actionable",
    }


def _perl_nth_formula_findings(path: str, text: str) -> list[dict[str, Any]]:
    if not all(token in text for token in ("sub _equation", "sub _pc", "$args->[0]", "$args->[1]", "_siblings")):
        return []

    loop = re.search(
        r"for\s+my\s+\$(?P<index>[A-Za-z_]\w*)\s*\(\s*0\s*\.\.\s*\$#siblings\s*\)\s*\{"
        r"(?P<body>[\s\S]{0,900}?)(?:\n\s*\}|\Z)",
        text,
        re.M,
    )
    if loop is None:
        return []
    index = re.escape(loop.group("index"))
    body = loop.group("body")
    generated = re.search(
        rf"\$args->\[0\]\s*\*\s*\${index}\s*\+\s*\$args->\[1\]",
        body,
    )
    indexed = re.search(r"\$siblings\s*\[\s*\$?[A-Za-z_]\w*\s*-\s*1\s*\]", body)
    early_end = re.search(r"return\s+undef\s+unless\s+my\s+\$[A-Za-z_]\w*\s*=\s*\$siblings", body)
    algebraic = re.search(
        r"(?:\$delta\s*%\s*\$args->\[0\]|\$index\s*-\s*\$args->\[1\])",
        text,
    )
    if generated is None or indexed is None or early_end is None or algebraic is not None:
        return []

    absolute = loop.start("body") + generated.start()
    return [
        _finding(
            officer="Engineer",
            capability="index_domain_contract",
            category="correctness",
            severity="major",
            root_cause="nth-selector-formula-enumerated-as-bounded-sibling-lookup",
            path=path,
            line_start=_line(text, absolute),
            message=(
                "An An+B positional selector is generated as a bounded sequence of sibling indexes instead of testing the current element's index algebraically."
            ),
            evidence=(
                "The matcher iterates n only across the sibling count, computes A*n+B, indexes the sibling array, and returns failure as soon as a generated position is outside the array. "
                "That search direction is not equivalent to the CSS An+B membership rule for zero, negative, sparse, or reverse-counted coefficients."
            ),
            falsifiers=[
                "Required parsed An+B coefficients and a sibling-position matcher in the same implementation.",
                "Required candidate positions to be generated by multiplying a loop counter by A and adding B.",
                "Required an early out-of-range failure while enumerating generated positions.",
                "Checked for direct current-index delta, sign, and divisibility validation.",
                "Excluded algebraic membership implementations and constant-position selectors.",
            ],
            verification=(
                "Determine the current one-based sibling index, convert reverse-counted selectors before evaluation, and accept exactly when index-B has the required sign and is divisible by A; test even, odd, zero, negative A, negative B, nth-last, and sparse sibling sets."
            ),
            confidence=0.99,
        )
    ]


def _fsharp_recursive_hash_findings(files: dict[str, str]) -> list[dict[str, Any]]:
    list_source = next(
        (
            (path, text)
            for path, text in files.items()
            if re.search(r"\btype\s+List\s*<\s*'T\s*>\s*=", text)
            and re.search(r"Tail\s*:\s*'T\s+list", text)
            and "StructuralEquality" in text
        ),
        None,
    )
    compiler_source = next(
        (
            (path, text)
            for path, text in files.items()
            if "MakeBindingsForEqualityWithComparerAugmentation" in text
            and "mkUnionHashWithComparer" in text
        ),
        None,
    )
    if list_source is None or compiler_source is None:
        return []

    list_path, list_text = list_source
    compiler_path, compiler_text = compiler_source
    generated = re.search(
        r"if\s+tycon\.IsUnionTycon\s+then\s+mkStructuralEquatable\s+mkUnionHashWithComparer",
        compiler_text,
    )
    custom_list_hash = "CustomHashCode" in list_text
    compiler_override = bool(
        re.search(r"list_tcr_canon[\s\S]{0,900}CustomHashCode", compiler_text)
        or re.search(r"CustomHashCode[\s\S]{0,900}list_tcr_canon", compiler_text)
    )
    if generated is None or custom_list_hash or compiler_override:
        return []

    list_decl = re.search(r"\btype\s+List\s*<\s*'T\s*>\s*=", list_text)
    support_line = _line(list_text, list_decl.start() if list_decl else 0)
    return [
        _finding(
            officer="Engineer",
            capability="performance",
            category="correctness",
            severity="blocker",
            root_cause="recursive-list-structural-hash-generated-without-tail-bounded-implementation",
            path=compiler_path,
            line_start=_line(compiler_text, generated.start()),
            message=(
                "A recursive list receives the generic recursive union hash implementation without an iterative or depth-bounded override."
            ),
            evidence=(
                "The core List type is a recursive discriminated union whose Tail is another list, while equality augmentation routes all union types through the generated structural union hash. "
                "No list-specific custom hash path is present, so hashing a sufficiently long list consumes one stack frame per node and can overflow the process stack."
            ),
            falsifiers=[
                "Required a recursive List union and compiler-generated structural hashing for unions.",
                "Checked the List declaration for an iterative CustomHashCode implementation.",
                "Checked the compiler augmentation for a canonical-list override.",
                "Excluded recursive types with explicit depth limits, iterative traversal, or a bounded custom hash path.",
            ],
            verification=(
                "Route the built-in recursive list to an iterative custom hash implementation and test empty, null-containing, differing-suffix, and lists larger than the former stack-overflow threshold while preserving equality/hash consistency."
            ),
            confidence=0.99,
            supporting=(f"{list_path}:{support_line}",),
        )
    ]


def _nim_deferred_free_findings(path: str, text: str) -> list[dict[str, Any]]:
    required = (
        "atomicPrepend",
        "sharedFreeListBigChunks",
        "freeDeferredObjects",
        "addToSharedFreeListBigChunks",
    )
    if not all(token in text for token in required):
        return []
    if "takeFromSharedFreeListBigChunks" in text:
        return []

    detach = re.search(
        r"atomicExchangeN\s*\(\s*addr\s+a\.sharedFreeListBigChunks\s*,\s*nil",
        text,
    )
    free_fn = re.search(
        r"proc\s+freeDeferredObjects\s*\([^)]*root\s*:\s*PBigChunk[^)]*\)\s*=\s*(?P<body>[\s\S]{0,1800}?)(?=\nwhen\s+defined\(heaptrack\)|\nproc\s+rawAlloc|\Z)",
        text,
    )
    prepend_overwrite = re.search(r"elem\.next\.storea\s+head\.loada", text)
    if detach is None or free_fn is None or prepend_overwrite is None:
        return []

    body = free_fn.group("body")
    rest = re.search(r"let\s+rest\s*=\s*it\.next(?:\.loada)?", body)
    bounded = re.search(r"(?:maxIters\s*=\s*MaxSteps|maxIters\s*==\s*0)", body)
    requeue = re.search(r"addToSharedFreeListBigChunks\s*\(\s*a\s*,\s*rest\s*\)", body)
    if rest is None or bounded is None or requeue is None:
        return []

    absolute = free_fn.start("body") + requeue.start()
    return [
        _finding(
            officer="Mechanic",
            capability="concurrency",
            category="concurrency",
            severity="blocker",
            root_cause="detached-linked-list-tail-requeued-through-prepend-loses-chain",
            path=path,
            line_start=_line(text, absolute),
            message=(
                "A bounded drain detaches an entire shared linked list and requeues the unprocessed tail through a prepend primitive that overwrites that tail node's next link."
            ),
            evidence=(
                "The allocator atomically exchanges the shared big-chunk head with nil, processes only MaxSteps nodes, and passes `rest` to `atomicPrepend`. "
                "That prepend writes the current head into `rest.next`; because `rest` is already the head of the remaining chain, the write discards every node after it and leaks the detached tail."
            ),
            falsifiers=[
                "Required whole-list detachment from the shared head before a bounded drain.",
                "Required the unprocessed remainder to retain a linked tail.",
                "Required requeue through a prepend operation that rewrites the inserted node's next pointer.",
                "Checked for pop-one/CAS consumption that never detaches more nodes than can be processed.",
                "Excluded unbounded drains and requeue operations that preserve the complete remainder chain.",
            ],
            verification=(
                "Atomically pop and detach one node at a time for at most the processing budget, then prove with more than MaxSteps deferred chunks and concurrent producers that every node remains reachable and occupied memory returns to zero."
            ),
            confidence=1.0,
            supporting=(
                f"{path}:{_line(text, detach.start())}",
                f"{path}:{_line(text, prepend_overwrite.start())}",
            ),
        )
    ]


def run_static_transfer_30_review(
    root: str | Path,
    changed_files: Iterable[str],
) -> dict[str, Any]:
    root_path = Path(root).resolve()
    changed = sorted({str(item) for item in changed_files if str(item)})
    readable: list[str] = []
    findings: list[dict[str, Any]] = []
    fsharp_files: dict[str, str] = {}

    for path in changed:
        suffix = Path(path).suffix.lower()
        if suffix not in _SOURCE_SUFFIXES:
            continue
        text = _safe_text(root_path, path)
        if not text:
            continue
        readable.append(path)
        if suffix in {".pl", ".pm"}:
            findings.extend(_perl_nth_formula_findings(path, text))
        elif suffix in {".fs", ".fsi", ".fsx"}:
            fsharp_files[path] = text
        elif suffix == ".nim":
            findings.extend(_nim_deferred_free_findings(path, text))

    findings.extend(_fsharp_recursive_hash_findings(fsharp_files))

    unique: dict[tuple[str, str, int], dict[str, Any]] = {}
    for finding in findings:
        unique[
            (
                str(finding.get("root_cause")),
                str(finding.get("path")),
                int(finding.get("line_start") or 0),
            )
        ] = finding

    return {
        "schema_version": "sergeant.static-transfer-30-review.v1",
        "mode": "model_free_static",
        "finding_count": len(unique),
        "findings": list(unique.values()),
        "readable_changed_files": readable,
        "executed_project_code": False,
    }
