function createActions({ workspaceRoot, activeRelativeFile, changedFilesCsv }) {
  return [
    {
      id: "reviewWorkspace",
      label: "Review Workspace",
      description: "Deterministic + Cpl specialist verdict",
      command: "sergeant.reviewWorkspace",
      title: "Sergeant workspace review",
      args: () => ["pr-review", workspaceRoot(), "--pretty"],
      page: "orders",
      kind: "primary",
    },
    {
      id: "appReviewWorkspace",
      label: "App Bridge Review",
      description: "Application contract review",
      command: "sergeant.appReviewWorkspace",
      title: "Sergeant app bridge review",
      args: () => ["app-review", workspaceRoot(), "--pretty"],
      page: "orders",
    },
    {
      id: "reviewCurrentFile",
      label: "Review Current File",
      description: "Editor-aware Cpl file review",
      command: "sergeant.reviewCurrentFile",
      title: "Sergeant current file review",
      args: async () => ["pr-review", workspaceRoot(), "--files", await activeRelativeFile(), "--pretty"],
      page: "orders",
    },
    {
      id: "reviewChangedFiles",
      label: "Review Changed Files",
      description: "Git changed-file Cpl review",
      command: "sergeant.reviewChangedFiles",
      title: "Sergeant changed files review",
      args: async () => ["pr-review", workspaceRoot(), "--files", await changedFilesCsv(), "--pretty"],
      page: "orders",
    },
    {
      id: "v2Mission",
      label: "V2 Mission",
      description: "Commander release-gate mission",
      command: "sergeant.v2Mission",
      title: "Sergeant V2 mission",
      args: () => ["v2-mission", workspaceRoot(), "--mission-type", "release_gate_review", "--pretty"],
      page: "orders",
    },
    {
      id: "proofSuite",
      label: "Proof Suite",
      description: "End-to-end proof",
      command: "sergeant.proofSuite",
      title: "Sergeant proof suite",
      args: () => ["proof-suite", workspaceRoot(), "--pretty"],
      page: "proof",
    },
    {
      id: "finalProof",
      label: "Final Proof",
      description: "Release gate",
      command: "sergeant.finalProof",
      title: "Sergeant final proof",
      args: () => ["final-proof", workspaceRoot(), "--pretty"],
      page: "proof",
      kind: "primary",
    },
    {
      id: "verifyStandard",
      label: "Verify Standard",
      description: "Evidence contract check",
      command: "sergeant.verifyStandard",
      title: "Sergeant standard verification",
      args: () => ["verify-standard", workspaceRoot(), "--pretty"],
      page: "proof",
    },
    {
      id: "battleTests",
      label: "Battle Tests",
      description: "Benchmark fixtures",
      command: "sergeant.battleTests",
      title: "Sergeant battle tests",
      args: () => ["battle-tests", workspaceRoot(), "--pretty"],
      page: "proof",
    },
    {
      id: "ideBenchContract",
      label: "IDE Contract",
      description: "Integration contract",
      command: "sergeant.ideBenchContract",
      title: "Sergeant IDE Bench contract",
      args: () => ["ide-bench-contract", "--pretty"],
      page: "doctrine",
    },
  ];
}

module.exports = { createActions };
