import { spawn } from "node:child_process";
import { mkdir, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";

const targetUrl=process.env.HUNTER_REVIEW_URL;if(!targetUrl)throw new Error('HUNTER_REVIEW_URL is required');
const outDir=process.env.PROOF_DIR||'artifacts/hunter-unaccounted';await mkdir(outDir,{recursive:true});
const chromePath=[process.env.CHROME_PATH,'/usr/bin/google-chrome','/usr/bin/google-chrome-stable','/usr/bin/chromium'].filter(Boolean).find(existsSync);if(!chromePath)throw new Error('Chrome missing');
const port=9257,chrome=spawn(chromePath,['--headless=new','--no-sandbox','--disable-gpu',`--remote-debugging-port=${port}`,`--user-data-dir=${join(process.env.RUNNER_TEMP||'/tmp',`srg-unaccounted-${Date.now()}`)}`,'--window-size=390,844','about:blank'],{stdio:['ignore','pipe','pipe']});let log='';chrome.stdout.on('data',d=>log+=String(d));chrome.stderr.on('data',d=>log+=String(d));const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function waitJson(url){for(let i=0;i<120;i++){try{const r=await fetch(url);if(r.ok)return r.json()}catch{}await sleep(250)}throw new Error(log.slice(-4000))}
let ws,id=0;const pending=new Map();function cdp(method,params={}){const n=++id;return new Promise((resolve,reject)=>{pending.set(n,{resolve,reject});ws.send(JSON.stringify({id:n,method,params}))})}async function ev(expression){const r=await cdp('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw new Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result?.value}async function waitFor(expression,label){for(let i=0;i<160;i++){try{if(await ev(expression))return}catch{}await sleep(100)}throw new Error(`Timed out ${label}`)}
try{const tabs=await waitJson(`http://127.0.0.1:${port}/json/list`),t=tabs.find(x=>x.type==='page')||tabs[0];ws=new WebSocket(t.webSocketDebuggerUrl);await new Promise((resolve,reject)=>{ws.addEventListener('open',resolve,{once:true});ws.addEventListener('error',reject,{once:true})});ws.addEventListener('message',e=>{const m=JSON.parse(String(e.data));if(!m.id||!pending.has(m.id))return;const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(new Error(JSON.stringify(m.error))):p.resolve(m.result||{})});await cdp('Runtime.enable');await cdp('Page.enable');await cdp('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:3,mobile:true,screenWidth:390,screenHeight:844});await cdp('Emulation.setTouchEmulationEnabled',{enabled:true,maxTouchPoints:5});await cdp('Emulation.setUserAgentOverride',{userAgent:'Mozilla/5.0 (iPhone; CPU iPhone OS 18_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.5 Mobile/15E148 Safari/604.1',platform:'iPhone'});await cdp('Page.navigate',{url:`${targetUrl}${targetUrl.includes('?')?'&':'?'}srg-unaccounted=${Date.now()}`});await waitFor("document.readyState==='complete'&&!!globalThis.__HUNTER_SERGEANT_UI__",'Sergeant runtime');await ev("globalThis.__HUNTER_SERGEANT_UI__.critical().then(()=>globalThis.__HUNTER_SERGEANT_UI__.report())");await sleep(300);const result=await ev(`(()=>({report:globalThis.__HUNTER_SERGEANT_UI__.report(),controls:[...document.querySelectorAll('[data-srg-unaccounted="true"]')].map((e,index)=>({index,tag:e.tagName,id:e.id||'',className:String(e.className||''),label:(e.getAttribute('aria-label')||e.title||e.textContent||e.value||'').replace(/\\s+/g,' ').trim(),dataset:{...e.dataset},attributes:[...e.attributes].map(a=>[a.name,a.value]),onclick:typeof e.onclick,outerHTML:e.outerHTML.slice(0,1200),parent:e.parentElement?.outerHTML?.slice(0,700)||''}))}))()`);await writeFile(join(outDir,'unaccounted.json'),JSON.stringify({targetUrl,result,capturedAt:new Date().toISOString()},null,2));console.log(JSON.stringify(result.controls,null,2));if(!result.controls.length)throw new Error('No unaccounted controls reproduced')}finally{try{ws?.close()}catch{}chrome.kill('SIGTERM');await sleep(250);if(!chrome.killed)chrome.kill('SIGKILL')}
